config/routes.rb
Rails.application.routes.draw do
  resources :shows, only: [:index, :show, :about]
  get 'about', to: 'pages#about', as: 'about'
  root 'shows#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/show.rb
class Show < ApplicationRecord
  include HTTParty
  include PgSearch
  validates_presence_of :name
  pg_search_scope :search_by_name, :against => [:name],
                  using: { :tsearch => { :prefix => true } }

  $movie_db_api_key = Rails.application.credentials.dig(:themoviedb, :api_key)
  $show_data_response = HTTParty.get("https://api.themoviedb.org/3/discover/tv?api_key=#{$movie_db_api_key}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&include_null_first_air_dates=false")
  $image_data_response = HTTParty.get("https://api.themoviedb.org/3/configuration?api_key=#{$movie_db_api_key}")
  $show_attributes = $show_data_response['results']
  $image_attributes = $image_data_response['images']

  $attributes = {
      1 => 'name',
      2 => 'vote_average',
      3 => 'origin_country',
      4 => 'first_air_date',
      5 => 'overview',
      6 => 'poster_path'
  }.freeze

  def self.poster_image_sizes
    $image_attributes.select do |k, _v|
      k == 'poster_sizes'
    end
  end

  def self.base_url
    $image_attributes['base_url']
  end

  def self.popular_shows
    show_objects = []
    $show_attributes.each do |show|
      show.select do |k, _v|
        $attributes.value?(k)
      end
      show_objects << show
    end
    fix_countries(show_objects)
  end

  def self.fix_countries(show_objects)
    show_objects.each do |show|
      unless show['origin_country'].nil? || show['origin_country'].first.nil?
        show['origin_country'] = NormalizeCountry(show['origin_country'].first)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def nav_bar_helper
    if current_page?(controller: 'shows', action: 'index')
      @class = "active"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about;end
  layout "home"
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  include ShowsHelper
  layout "home"
  before_action :update_popular_shows

  def index
    if params[:search]
      @search_results_shows = Show.search_by_name(params[:search])
      respond_to do |format|
        format.js { render partial: 'shared/search-results' }
      end
    else
      @shows = Show.all
    end
  end

  def show
    if params[:search]
      @search_results_shows = Show.search_by_name(params[:search])
      respond_to do |format|
        format.js { render partial: 'shared/search-results' }
      end
    else
      @show = @shows.find(params[:id])
    end
  end

  private

  def show_params
    params.require(:show).permit(:name, :vote_average, :origin_country, :first_air_date, :overview, :poster_path)
  end

  def update_popular_shows
    @base_url = Show.base_url
    @shows = Show.all
    @popular_shows = Show.popular_shows
    @popular_shows.each do |show|
      next unless @shows.find_by(name: show["name"]).nil?
      Show.create(name: show["name"],
                  vote_average: show["vote_average"],
                  origin_country: show["origin_country"],
                  first_air_date: show["first_air_date"],
                  overview: show["overview"],
                  poster_path: show["poster_path"]).save!
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def copyright_generator
    CorleyViewTool::Renderer.copyright 'John Corley', "All Rights Reserved."
  end
end

app/helpers/shows_helper.rb
module ShowsHelper

  def self.image_url_builder(base_url, poster_path, poster_size = 'w500')
    "#{base_url}#{poster_size}#{poster_path}".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movieportal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render partial: 'shared/navbar' %>

  <body>
    <%= yield %>
    <div id="search-results"></div>

    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about-page-content">
  <h1>Welcome to the Movie Portal!</h1>
  <div class="grid-container" >
    <div class="about-grid-item">The Movie Portal is a Ruby on Rails application created by Jack Corley. It was created to
      leverage the MovieDB API. From the home page you can access an index of the most popular TV shows to date. Also
      feel
      free to use the search bar to filter the results from the most popular tv shows.
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= copyright_generator %>
</div>

app/views/shared/_navbar.html.erb
<div class="topnav">
  <%= link_to "Home", '/' %>
  <%= link_to "About", about_path %>
  <div class="search-container">
    <%= render partial: "shared/search" %>
  </div>
</div>

app/views/shared/_results.html.erb
<div class="main-card">
  <h1>Search Results</h1>
  <div class="grid-container", id="shows-grid">
    <% @search_results_shows.each do |show| %>
      <div class="grid-item-link"><%= link_to "#{show.name}", show %></div>
    <% end  %>
  </div>
</div>

app/views/shared/_search-results.js.erb
$("#shows-grid").hide();
$("#home-header").hide();
$("#about-page-content").hide();
$("#home-header").hide();
$("#show-instance").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'shared/results') %>");

app/views/shared/_search.html.erb
<%= form_tag(shows_path, method: "get", remote: true) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
  <%= button_tag "", class: "fa fa-search" %>
<% end %>

app/views/shows/index.html.erb
<div id="show-index">
  <h1 id="home-header">TV's Top Twenty</h1>
  <div class="grid-container", id="shows-grid">
    <% @shows.each do |show| %>
      <div class="grid-item-link"><%= link_to "#{show.name}", show %></div>
    <% end  %>
  </div>
</div>

app/views/shows/show.html.erb
<div  id="show-instance">

  <h1 id="show-name"><%= @show.name %></h1>
  <div id="show-poster"><%= image_tag(ShowsHelper.image_url_builder(@base_url, @show.poster_path)) %></div>

  <div id="show-overview"><%= @show.overview %></div>

  <div id="more-details">
    <div id="show-rating"><%= @show.vote_average %></div>
    <div id="show-country-origin"><%= @show.origin_country %></div>
    <div id="shows-first-air-date"><%= @show.first_air_date %></div>
  </div>

</div>